### ISSUE TITLE
How to hire or be hired

### ISSUE THREAD

**Issue by amweiss** [amweiss/amweiss.github.io#2]

**Comment by colin-higgins** [comment]
Is this more of a what hiring managers look for? Or methodologies for both? Because that could be a really big article.

I'd be pretty interested in hearing about a "good" interview process.

**Comment by amweiss** [comment]
I was thinking both, but you're right this should be two separate ones.

**Comment by amweiss** [comment]
First of many at http://adamweiss.me/leadership/hiring-people-shouldnt-be-this-hard/
